---
- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  when: packge_cleanup_autoclean == "yes"

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  when: packge_cleanup_autoremove == "yes"